name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: npm
      - name: Install
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          npm --prefer-offline --frozen-lockfile --no-progress --non-interactive
      - name: Format check
        run: npm run format:check
      - name: Lint
        run: npm run lint
      - name: Test Server
        run: 'cd packages/server && npm test'
      - name: Test Client
        run: 'cd packages/client && npm test'
